# SUDOKU SOLVER

## LeetCode coding challenge number 37

### MOISES BARBERA RAMOS    -     https://www.linkedin.com/in/moises-barbera-ramos-8a3848164/


Write a program to solve a Sudoku puzzle by filling the empty cells.

A sudoku solution must satisfy all of the following rules:

    - Each of the digits 1-9 must occur exactly once in each row.
    - Each of the digits 1-9 must occur exactly once in each column.
    - Each of the the digits 1-9 must occur exactly once in each of the 9 3x3 sub-boxes of the grid.
    - Empty cells are indicated by the character '.'.

In [ ]:
class Solution:
    
    def single_finder(self, board, y, x, n):
      
        for i in range(0, 9):
            if board[y][i] == str(n):
                return False           # This loop checks if n is on the x axis (row) chosen by y

        for i in range(0, 9):
            if board[i][x] == str(n):
                return False           # This loop checks if n is on the y axis (column) chosen by x

        x_0 = (x//3) * 3
        y_0 = (y//3) * 3

        for i in range(0, 3):
            for j in range(0, 3):
                if board[y_0 + i][x_0 + j] == str(n):
                    return False      # This last set of loops checks if n is in eache of the squares of 9 inputs
        return True

    def solveSudoku(self, board: List[List[str]]) -> None:          # Recursive algorithm using the previous function
            

        for y in range(9):
            for x in range(9):
                if board[y][x] == ".":            # Check if the coordinates x and y are 0 (empty)
                    for n in range(1,10):           
                        if self.single_finder(board, y, x, n):   # If xy is empty (0) do the previous funtion recursively
                                                                # for all possible values in a sudoku from 1 to 9
                            board[y][x] = str(n)     # if n is accepted as the solution at that position

                            if self.solveSudoku(board):
                                return 1
                            else:
                                board[y][x] = "."
                    return 0
        return 1
    

#### Result from submission:

Runtime: 1052 ms, faster than 7.39% of Python3 online submissions for Sudoku Solver.

Memory Usage: 13.7 MB, less than 10.71% of Python3 online submissions for Sudoku Solver


## Step by Step solution using a more visual method:

In [1]:
# Loading sudoku input from LeetCode - testcase

str_sudoku = [["5","3",".",".","7",".",".",".","."],["6",".",".","1","9","5",".",".","."],[".","9","8",".",".",".",".","6","."],["8",".",".",".","6",".",".",".","3"],["4",".",".","8",".","3",".",".","1"],["7",".",".",".","2",".",".",".","6"],[".","6",".",".",".",".","2","8","."],[".",".",".","4","1","9",".",".","5"],[".",".",".",".","8",".",".","7","9"]]

In [2]:
# Substitute all dots by 0s so later we can use only manipulation of integers rather than integers and strings.

str_sudoku_0 = str(str_sudoku).replace(".", "0")
str_sudoku_0

"[['5', '3', '0', '0', '7', '0', '0', '0', '0'], ['6', '0', '0', '1', '9', '5', '0', '0', '0'], ['0', '9', '8', '0', '0', '0', '0', '6', '0'], ['8', '0', '0', '0', '6', '0', '0', '0', '3'], ['4', '0', '0', '8', '0', '3', '0', '0', '1'], ['7', '0', '0', '0', '2', '0', '0', '0', '6'], ['0', '6', '0', '0', '0', '0', '2', '8', '0'], ['0', '0', '0', '4', '1', '9', '0', '0', '5'], ['0', '0', '0', '0', '8', '0', '0', '7', '9']]"

In [3]:
# Clean the sudoku grid by removing the newly appeared string denotation outside the main list

import ast
str_sudoku_0 = ast.literal_eval(str_sudoku_0)
str_sudoku_0

[['5', '3', '0', '0', '7', '0', '0', '0', '0'],
 ['6', '0', '0', '1', '9', '5', '0', '0', '0'],
 ['0', '9', '8', '0', '0', '0', '0', '6', '0'],
 ['8', '0', '0', '0', '6', '0', '0', '0', '3'],
 ['4', '0', '0', '8', '0', '3', '0', '0', '1'],
 ['7', '0', '0', '0', '2', '0', '0', '0', '6'],
 ['0', '6', '0', '0', '0', '0', '2', '8', '0'],
 ['0', '0', '0', '4', '1', '9', '0', '0', '5'],
 ['0', '0', '0', '0', '8', '0', '0', '7', '9']]

In [4]:
# Go though all the elements in each sublist and check if it is a digit/number or not. 
# If it is a digit, substitute the string by an int. Else leave the element as a string.

for idx, sublist in enumerate(str_sudoku_0):
     str_sudoku_0[idx] = [
         int(el) if el.isdigit() else el
         for el in sublist
     ]
        
int_sudoku = str_sudoku_0.copy()  # Print the cleaned grid formed out of integers
int_sudoku

[[5, 3, 0, 0, 7, 0, 0, 0, 0],
 [6, 0, 0, 1, 9, 5, 0, 0, 0],
 [0, 9, 8, 0, 0, 0, 0, 6, 0],
 [8, 0, 0, 0, 6, 0, 0, 0, 3],
 [4, 0, 0, 8, 0, 3, 0, 0, 1],
 [7, 0, 0, 0, 2, 0, 0, 0, 6],
 [0, 6, 0, 0, 0, 0, 2, 8, 0],
 [0, 0, 0, 4, 1, 9, 0, 0, 5],
 [0, 0, 0, 0, 8, 0, 0, 7, 9]]

In [5]:
import numpy as np
print(np.matrix(int_sudoku))   # Display neatly the structure of the sudoku to solve where each 0 is a blank space to fill.

[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 7 9]]


In [6]:
# Function determining wether at a given position (blank space), we can put a number n

def single_finder(y, x, n):
    
    global int_sudoku  # allows us to modify a variable outside of the current scope. Inside this funtion in our case
    
    for i in range(0, 9):
        if int_sudoku[y][i] == n:
            return False           # This loop checks if n is on the x axis (row) chosen by y
        
    for i in range(0, 9):
        if int_sudoku[i][x] == n:
            return False           # This loop checks if n is on the y axis (column) chosen by x
        
    x_0 = (x//3) * 3
    y_0 = (y//3) * 3
    
    for i in range(0, 3):
        for j in range(0, 3):
            if int_sudoku[y_0 + i][x_0 + j] == n:
                return False      # This last set of loops checks if n is in eache of the squares of 9 inputs
    return True

In [7]:
def total_finder():          # Recursive algorithm using the previous function
    
    global int_sudoku        # allows us to modify a variable outside of the current scope.
    
    for y in range(9):
        for x in range(9):
            if int_sudoku[y][x] == 0:            # Check if the coordinates x and y are 0 (empty)
                for n in range(1,10):           
                    if single_finder(y, x, n):   # If xy is empty (0) do the previous funtion recursively
                                                    # for all possible values in a sudoku from 1 to 9
                        
                        int_sudoku[y][x] = n     # if n is accepted as the solution at that position
                        
                        total_finder()           # then run this function recursively for the next empty square
                        
                        int_sudoku[y][x] = 0     # to backtest, if there has been some wrong decision,
                                                    #make the given square again.
                return
            
    print(np.matrix(int_sudoku))                 # Print the resulting solved sudoku
    input("Are there more solutions? (Press enter to find out)")    # If there are more solutions to any sudoku,
                                                                        # re-run by pressing enter 

In [ ]:
total_finder()

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
